### ISSUE TITLE
Em không cài được ctc_decoders

### ISSUE THREAD

**Issue by canonsky1992** [dangvansam98/viet-asr#2]
Bác hướng dẫn e với ModuleNotFoundError: BeamSearchDecoderWithLM requires the installation of ctc_decoders from nemo/scripts/install_decoders.py. Chạy install_decoders.sh vẫn ko được bác ạ

**Comment by nguyendohoangkhoi** [comment]
> 

sao mình làm như bạn nói rồi mà vẫn không được nhỉ. Chạy lại vẫn không tìm thấy module ctc_decoders

**Comment by dangvansam98** [comment]
> > 
> 
> sao mình làm như bạn nói rồi mà vẫn không được nhỉ. Chạy lại vẫn không tìm thấy module ctc_decoders

Mình đã update lại repo fix các lỗi mà các bạn gặp phải khi cài đặt cũng như chạy hệ thống, bạn có thể thử lại nhé

**Comment by dangvansam98** [comment]
Updated: https://github.com/dangvansam98/viet-asr
