### ISSUE TITLE
Requirement.txt

### ISSUE THREAD

**Issue by ThanhPham1987** [dangvansam98/viet-asr#4]
Hi ban,

Ban co the cung cap file requirement.txt khong?

Best reagrds,

PeterPham

**Comment by dangvansam98** [comment]
> Hi ban,
> 
> Ban co the cung cap file requirement.txt khong?
> 
> Best reagrds,
> 
> PeterPham

Mình gửi bạn file [requirements.txt](https://github.com/dangvansam98/viet-asr/blob/main/requirements.txt)
